apiVersion: v1
kind: Service
metadata:
  name: node-oauth-service
  labels:
    app: node-oauth
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 5050
      protocol: TCP
      name: node-oauth-svc-port
  selector:
    app: node-oauth
