apiVersion: v1
kind: Service
metadata:
  name: node-oauth-service-nodeport
  labels:
    app: node-oauth
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 5050
      protocol: TCP
      name: node-oauth-svc-port
  selector:
    app: node-oauth
